<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="din83000439" failures="8" tests="28" name="EmployeesRestAPITest" time="22.745" errors="0" timestamp="2022-06-14T08:53:57 IST">
  <testcase classname="com.employees.testCases.TC005_Delete_Employee_Record" name="@BeforeClass deleteEmployee" time="0.876">
    <failure type="io.restassured.path.json.exception.JsonPathException" message="Failed to parse the JSON document">
      <![CDATA[io.restassured.path.json.exception.JsonPathException: Failed to parse the JSON document
at io.restassured.path.json.JsonPath$ExceptionCatcher.invoke(JsonPath.java:1002)
at io.restassured.path.json.JsonPath$4.doParseWith(JsonPath.java:967)
at io.restassured.path.json.JsonPath$JsonParser.parseWith(JsonPath.java:1047)
at io.restassured.path.json.JsonPath.get(JsonPath.java:202)
at com.employees.testCases.TC005_Delete_Employee_Record.deleteEmployee(TC005_Delete_Employee_Record.java:43)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
Caused by: groovy.json.JsonException: Lexing failed on line: 1, column: 1, while reading '<', no possible valid JSON value or punctuation could be recognized.
at groovy.json.JsonLexer.nextToken(JsonLexer.java:86)
at groovy.json.JsonLexer$nextToken.call(Unknown Source)
at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:46)
at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:125)
at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:130)
at io.restassured.internal.path.json.ConfigurableJsonSlurper.parse(ConfigurableJsonSlurper.groovy:97)
at io.restassured.internal.path.json.ConfigurableJsonSlurper$parse.callCurrent(Unknown Source)
at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCallCurrent(CallSiteArray.java:50)
at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callCurrent(AbstractCallSite.java:171)
at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callCurrent(AbstractCallSite.java:185)
at io.restassured.internal.path.json.ConfigurableJsonSlurper.parseText(ConfigurableJsonSlurper.groovy:83)
at io.restassured.path.json.JsonPath$4$1.method(JsonPath.java:965)
at io.restassured.path.json.JsonPath$ExceptionCatcher.invoke(JsonPath.java:1000)
... 30 more
... Removed 25 stack frames]]>
    </failure>
  </testcase> <!-- @BeforeClass deleteEmployee -->
  <testcase classname="com.employees.testCases.TC005_Delete_Employee_Record" name="@AfterClass tearDown" time="0.0">
    <skipped/>
  </testcase> <!-- @AfterClass tearDown -->
  <testcase classname="com.employees.testCases.TC_001_Get_All_Employees" name="checkContentLenght" time="0.01"/>
  <testcase classname="com.employees.testCases.TC_001_Get_All_Employees" name="checkContentType" time="0.004">
    <failure type="junit.framework.ComparisonFailure" message="expected:&amp;lt;application/json&amp;gt; but was:&amp;lt;text/html; charset=UTF-8&amp;gt;">
      <![CDATA[junit.framework.ComparisonFailure: expected:<application/json> but was:<text/html; charset=UTF-8>
at junit.framework.Assert.assertEquals(Assert.java:81)
at junit.framework.Assert.assertEquals(Assert.java:87)
at com.employees.testCases.TC_001_Get_All_Employees.checkContentType(TC_001_Get_All_Employees.java:91)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 27 stack frames]]>
    </failure>
  </testcase> <!-- checkContentType -->
  <testcase classname="com.employees.testCases.TC_001_Get_All_Employees" name="checkResponseBody" time="0.027"/>
  <testcase classname="com.employees.testCases.TC_001_Get_All_Employees" name="checkResponseTime" time="0.005"/>
  <testcase classname="com.employees.testCases.TC_001_Get_All_Employees" name="checkStatusCode" time="0.008"/>
  <testcase classname="com.employees.testCases.TC_001_Get_All_Employees" name="checkcontentEncoding" time="0.006"/>
  <testcase classname="com.employees.testCases.TC_001_Get_All_Employees" name="checkstatusLine" time="0.006"/>
  <testcase classname="com.employees.testCases.TC002_Get_Single_Employee_Record" name="checkContentLenght" time="0.006"/>
  <testcase classname="com.employees.testCases.TC002_Get_Single_Employee_Record" name="checkContentType" time="0.002"/>
  <testcase classname="com.employees.testCases.TC002_Get_Single_Employee_Record" name="checkResponseTime" time="0.003"/>
  <testcase classname="com.employees.testCases.TC002_Get_Single_Employee_Record" name="checkResposeBody" time="0.027">
    <failure type="java.lang.AssertionError" message="expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at com.employees.testCases.TC002_Get_Single_Employee_Record.checkResposeBody(TC002_Get_Single_Employee_Record.java:44)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 33 stack frames]]>
    </failure>
  </testcase> <!-- checkResposeBody -->
  <testcase classname="com.employees.testCases.TC002_Get_Single_Employee_Record" name="checkStatusCode" time="0.003">
    <failure type="java.lang.AssertionError" message="expected [200] but found [429]">
      <![CDATA[java.lang.AssertionError: expected [200] but found [429]
at com.employees.testCases.TC002_Get_Single_Employee_Record.checkStatusCode(TC002_Get_Single_Employee_Record.java:51)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 33 stack frames]]>
    </failure>
  </testcase> <!-- checkStatusCode -->
  <testcase classname="com.employees.testCases.TC002_Get_Single_Employee_Record" name="checkstatusLine" time="0.001">
    <failure type="java.lang.AssertionError" message="expected [HTTP/1.1 200 OK] but found [HTTP/1.1 429 Too Many Requests]">
      <![CDATA[java.lang.AssertionError: expected [HTTP/1.1 200 OK] but found [HTTP/1.1 429 Too Many Requests]
at com.employees.testCases.TC002_Get_Single_Employee_Record.checkstatusLine(TC002_Get_Single_Employee_Record.java:65)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 33 stack frames]]>
    </failure>
  </testcase> <!-- checkstatusLine -->
  <testcase classname="com.employees.testCases.TC003_Post_Employee_Record" name="checkContentEncoding" time="0.002"/>
  <testcase classname="com.employees.testCases.TC003_Post_Employee_Record" name="checkContentType" time="0.001"/>
  <testcase classname="com.employees.testCases.TC003_Post_Employee_Record" name="checkResponseBody" time="0.002">
    <failure type="java.lang.AssertionError" message="expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at com.employees.testCases.TC003_Post_Employee_Record.checkResponseBody(TC003_Post_Employee_Record.java:66)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 33 stack frames]]>
    </failure>
  </testcase> <!-- checkResponseBody -->
  <testcase classname="com.employees.testCases.TC003_Post_Employee_Record" name="checkStatusCode" time="0.001">
    <failure type="java.lang.AssertionError" message="expected [200] but found [429]">
      <![CDATA[java.lang.AssertionError: expected [200] but found [429]
at com.employees.testCases.TC003_Post_Employee_Record.checkStatusCode(TC003_Post_Employee_Record.java:75)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 33 stack frames]]>
    </failure>
  </testcase> <!-- checkStatusCode -->
  <testcase classname="com.employees.testCases.TC003_Post_Employee_Record" name="checkStatusLine" time="0.001">
    <failure type="java.lang.AssertionError" message="expected [HTTP/1.1 200 OK] but found [HTTP/1.1 429 Too Many Requests]">
      <![CDATA[java.lang.AssertionError: expected [HTTP/1.1 200 OK] but found [HTTP/1.1 429 Too Many Requests]
at com.employees.testCases.TC003_Post_Employee_Record.checkStatusLine(TC003_Post_Employee_Record.java:82)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 33 stack frames]]>
    </failure>
  </testcase> <!-- checkStatusLine -->
  <testcase classname="com.employees.testCases.TC004_Put_Employee_Record" name="checkContentEncoding" time="0.002">
    <failure type="java.lang.AssertionError" message="expected [gzip] but found [null]">
      <![CDATA[java.lang.AssertionError: expected [gzip] but found [null]
at com.employees.testCases.TC004_Put_Employee_Record.checkContentEncoding(TC004_Put_Employee_Record.java:96)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 33 stack frames]]>
    </failure>
  </testcase> <!-- checkContentEncoding -->
  <testcase classname="com.employees.testCases.TC004_Put_Employee_Record" name="checkContentType" time="0.002"/>
  <testcase classname="com.employees.testCases.TC004_Put_Employee_Record" name="checkResponseBody" time="0.002"/>
  <testcase classname="com.employees.testCases.TC004_Put_Employee_Record" name="checkStatusCode" time="0.001"/>
  <testcase classname="com.employees.testCases.TC004_Put_Employee_Record" name="checkStatusLine" time="0.001"/>
  <testcase classname="com.employees.testCases.TC005_Delete_Employee_Record" name="checkContentEncoding" time="0.0">
    <skipped/>
  </testcase> <!-- checkContentEncoding -->
  <testcase classname="com.employees.testCases.TC005_Delete_Employee_Record" name="checkContentType" time="0.0">
    <skipped/>
  </testcase> <!-- checkContentType -->
  <testcase classname="com.employees.testCases.TC005_Delete_Employee_Record" name="checkResponseBody" time="0.0">
    <skipped/>
  </testcase> <!-- checkResponseBody -->
  <testcase classname="com.employees.testCases.TC005_Delete_Employee_Record" name="checkStatusCode" time="0.0">
    <skipped/>
  </testcase> <!-- checkStatusCode -->
  <testcase classname="com.employees.testCases.TC005_Delete_Employee_Record" name="checkStatusLine" time="0.0">
    <skipped/>
  </testcase> <!-- checkStatusLine -->
</testsuite> <!-- EmployeesRestAPITest -->
